# Generated by Django 4.2.11 on 2026-03-03 05:17

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('years', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkloadAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('research_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('admin_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('academic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_allocations', to='academics.academic')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_allocations', to='years.academicyear')),
            ],
            options={
                'db_table': 'allocations_workloadallocation',
            },
        ),
        migrations.AddConstraint(
            model_name='workloadallocation',
            constraint=models.CheckConstraint(check=models.Q(('teaching_hours__gte', 0), ('research_hours__gte', 0), ('admin_hours__gte', 0)), name='allocations_hours_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='workloadallocation',
            unique_together={('academic', 'academic_year')},
        ),
    ]
