# Generated by Django 4.2.11 on 2026-04-18 12:10

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_alter_moduleteachingallocation_percentage'),
        ('allocations', '0003_alter_workloadallocation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingAllocationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=5)),
                ('calculated_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_items', to='modules.module')),
                ('workload_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_items', to='allocations.workloadallocation')),
            ],
            options={
                'db_table': 'allocations_teachingallocationitem',
                'ordering': ['module__name'],
                'unique_together': {('workload_allocation', 'module')},
            },
        ),
    ]
