# Generated by Django 4.2.11 on 2026-03-03 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('credit_hours', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='departments.department')),
            ],
            options={
                'db_table': 'modules_module',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibilities', to='academics.academic')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibilities', to='modules.module')),
            ],
            options={
                'db_table': 'modules_eligibility',
                'unique_together': {('academic', 'module')},
            },
        ),
    ]
